### ISSUE TITLE
More SIF types are listed than we actually use

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pcviz#28]
The list of interaction types  (initial I think) is here:
https://github.com/PathwayCommons/pcviz/blob/master/src/main/webapp/index.jsp#L290

But, the PC2 service, in fact, makes only three types (as far as I understand how SIFSearcher works):
https://github.com/PathwayCommons/pcviz/blob/master/src/main/java/org/pathwaycommons/pcviz/service/PathwayCommonsGraphService.java#L216

Attn: @armish @onursumer

**Comment by armish** [comment]
Yeah, those are just left-overs. We started with more edge types and then narrowed it down to the ones we have right now due to information overload. 

That design is terrible (sorry!) and I wish I had those edge types configurable from the `properties` file instead of hard-coding them. Please feel free to implement the approach whatever you think is the best.

**Comment by IgorRodchenkov** [comment]
Ok, got it. No worries, no regret - the design is not "terrible" at all :)) Thanks. I am going to remove unused types from that list.
