### ISSUE TITLE
it's almost impossible for some genes

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pcviz#29]
For example, a fresh test pcviz at pathwaycommons.baderlab.org/pcviz/ (that connects to PC2v8 and have no cache yet) can barely process some gene symbols, such as CYP26A1 (it takes a lot of minutes to build and visualize the network.. of ~6000 nodes). And that's just using a single gene!

Official PC2v7 pcviz - with pre-calculated data for uniprot, running at pathwaycommons.org/pcviz/ (or, another one, - at sanderlab.org/pcviz/) - just returns one single node, which probably flags for errors (give-ups due to timeout or error) during the uniprot-scraper.sh script run (CYP26A1 is the gene symbol for O43174).

The actual query that a pcviz app sends to PC2 server, 
http://pathwaycommons.baderlab.org/graph?kind=neighborhood&source=CYP26A1
, returns 44MB of BioPAX (btw, using ...&source=O43174 would get "just" ~1MB and much faster, but still not fast enough; and these two queries are not equivalent).

Looks, what takes so much time is neither querying (fast) and downloading the data (well, it takes about a minute) nor even pcviz's biopax-to-sif converter (from Paxtools pattern lib.), but probably it's something in the javascripts and js libraries (perhaps, naturally...)

In comparison, the following query returns SIF in a couple of seconds despite it applies more SIF rules/types than pcviz (only uses three types at the moment):
http://pathwaycommons.baderlab.org/graph?kind=neighborhood&source=CYP26A1&format=binary_sif
(aye, I know, having just SIF is not quite sufficient for pcviz at the moment, anyway...)

PS:
We'd better re-design PCViz (might other our html5 apps as well), or at least clearly mark and explain applicability and limits, and, e.g., always drop huge networks after some timeout. If we go to re-design, we'd make it consume cytoscape.js/JSON network models directly from the, e.g., PC2 web service, which (the graph queries), of course, should be considerably modified to provide such output. Some things should definitely happen on the server side, where it works fast, not on the client's, alright, and we just have to design and plan which (type, format) to add/use instead of rushing into development of web apps that consume tons of merely raw network data and then struggle trying to write in js and execute quite complex algorithms. Any ideas?

Attn: @onursumer @ozgunbabur @armish @gbader @jvwong

**Comment by armish** [comment]
thanks for tracking this performance problem down to the details, @IgorRodchenkov! Happy to discuss other design strategies if we ever get to re-design it ;)

**Comment by IgorRodchenkov** [comment]
Gary suggested we ask @maxkfranz for advise, because we probably have to upgrade to the latest Cytoscape.js and also make sure we use it properly; i.e., do not layout/animate each individual node or smth... Thanks @armish Arman!

**Comment by armish** [comment]
yeah, that sounds like a good idea. The cytoscape.js we use within PCViz is pretty out-dated now :+1:

**Comment by maxkfranz** [comment]
Copied from email:

## 

Summary : Just update Cytoscape.js to >=2.6 and use the CoSE layout, and you should be fine.

There's something missing from the deployment instructions, maybe in environment, because PCViz just gets errors when I deploy locally.  So, I can't test any changes.

Instead, I just profiled your beta site and browsed the code a little.  

From the code: You're using one of the first versions of Cytoscape.js, and you're using the Arbor layout.  Arbor is pretty much the worst possible layout to use, and Cytoscape.js should certainly be upgraded.

Profiling shows your slowdowns are (1) layout and (2) style calculation.  

(1) You need to use a better layout anyway.  CoSE is near instant, and it gives good results.  CoSE-Bilkent and Cola are layouts to try if CoSE doesn't give you the visual results you want, but they are not as fast.  We use CoSE on the new GeneMANIA.  Since the data is focussed on a few specified genes of interest, you could also use the concentric layout with the search genes in the centre.  Concentric is a near zero expense layout.

(2) Style calculation is generally expensive.  That's just how stylesheets work.  However, Cy.js 2.4, 2.5/2.6, and 2.7 have lots of complex optimisations for style (the same optimisations Safari and Chrome have for HTML/CSS stylesheets).  Upgrading should fix this.

While you could upgrade to the latest 2.6 and it would be OK, there are major rendering and style performance improvements in 2.7.  I have one minor bug to address before 2.7 is released.  If you can wait for a few days, I suggest you wait and use 2.7.

Aside : Could you remove the panzoom control on the top left?  It's old fashioned, and not really needed.  If you're concerned about accessibility, recent versions of the panzoom extension allow for showing only the zoom in and out buttons for users without touchscreens or a mousewheel.

**Comment by armish** [comment]
thanks a lot for taking a look at the current infrastructure and also for your suggestions, @maxkfranz! A student of @ugurdogrusoz has come up with that custom arbor layout to help us get the view we wanted, but to be honest, I didn't know that we now have better options out there.

@IgorRodchenkov: is it you who is going to do the upgrade and migration? Or do we have somebody else to help with all these?

**Comment by IgorRodchenkov** [comment]
Arman, I can do this (at least merge and polish) after hopefully Max make
most changes and submits a pull request (or helps me face2face to do what
should be done about cytoscape.js there...). This would be the fastest path.

**Comment by armish** [comment]
Sounds like a plan! Let me know if you need an extra pair of hands. I am away next week; but the following week will work fine: we can set a date and pair up to get things done.

**Comment by IgorRodchenkov** [comment]
Arman, we're trying to have this done this week or so or give up until next pc2 release... I don't mind (will be happy) if you'd do those changes together with Max right away! Sure you're more than welcome next next weeks if we delay, or in any case, no doubt. Thank you.

Igor

**Comment by armish** [comment]
gotcha - best of luck, then! :+1:

**Comment by maxkfranz** [comment]
I've updated Cy.js and set the CoSE layout.  As I've said before, I can't test so either @armish or @IgorRodchenkov is going to have to test/tweak this.

When I deploy the server, it never returns results.  It just times out.  I'm running the latest JVM and maven.  I have lots of other things to do, and don't have time to play around with config/env issues.

**Comment by IgorRodchenkov** [comment]
Thanks @maxkfranz ! I'll try it. (If you've tried only CYP26A1/O43174 ID, then it might timeout, though - no idea what's going on yet...; have you tried other IDs, such as e.g., BRCA1;  checked the PC2 URL in pcviz.properties is ok, etc.? Anyway, let me do it...)

**Comment by IgorRodchenkov** [comment]
It's much much faster now (js part). But we'd optimize getting data from controllers, converting to SIF, etc. (possibly delegate most work to PC2 services - to return rich JSON data ready for processing by Cytoscape.js), and then we'd close this issue...

**Comment by IgorRodchenkov** [comment]
This is still a problem for more than one gene name/id... But works for CYP26A1 and other pre-calculated... Closed.
